# Data Cleaning Exercise

Cleaning your data is crucial when starting a new data engineering project because it ensures the accuracy, consistency, and reliability of the dataset. Dirty data, which may include duplicates, missing values, and errors, can lead to incorrect analysis and insights, ultimately affecting the decision-making process. Data cleaning helps in identifying and rectifying these issues, providing a solid foundation for building effective data models and analytics. Additionally, clean data improves the performance of algorithms and enhances the overall efficiency of the project, leading to more trustworthy and actionable results.

Use Python, ```numpy```, ```pandas``` and/or ```matplotlib``` to analyse and clean your batch data:

## Import Libraries

In [1]:
# TODO

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Load Data

Link to data source: ```<TODO>```

In [2]:
# TODO
data=pd.read_csv('amazon-products-electronics-sales-2023.csv')

## Understand the Data

View the first few rows, get summary statistics and check data types

In [3]:
# TODO
data.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,4.0,965,"₹10,999","₹18,999"
1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,4.3,"113,956","₹18,999","₹19,999"
2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,4.2,"90,304","₹1,999","₹2,299"
3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,4.1,"24,863","₹15,999","₹24,999"
4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,4.3,"113,956","₹18,999","₹19,999"

In [4]:
data.shape

(9600, 9)

In [5]:
# Check datatypes
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9600 entries, 0 to 9599
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            9600 non-null   str
 1   main_category   9600 non-null   str
 2   sub_category    9600 non-null   str
 3   image           9600 non-null   str
 4   link            9600 non-null   str
 5   ratings         9505 non-null   str
 6   no_of_ratings   9505 non-null   str
 7   discount_price  9116 non-null   str
 8   actual_price    9530 non-null   str
dtypes: str(9)
memory usage: 675.1 KB

In [6]:
data.describe()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
count,9600,9600,9600,9600,9600,9505,9505,9116,9530
unique,8800,1,1,9321,9600,39,3455,1608,1068
top,TAGG Verve Sense Smartwatch with 1.70'' Large ...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61ARj+szfW...,https://www.amazon.in/Redmi-Power-Black-128GB-...,4.3,1,₹299,₹999
freq,9,9600,9600,7,1,1310,51,481,1540

## Handle Missing Data

Identify missing values and fill or drop missing values

In [7]:
# TODO
data.isnull().sum()

name                0
main_category       0
sub_category        0
image               0
link                0
ratings            95
no_of_ratings      95
discount_price    484
actual_price       70
dtype: int64

We delete the missing values of ratings and actual_price because we have enough other remaining datarecords for our purposes.

In [8]:
data = data.dropna(subset=['ratings', 'actual_price'])

In [9]:
data.isnull().sum()

name                0
main_category       0
sub_category        0
image               0
link                0
ratings             0
no_of_ratings       0
discount_price    409
actual_price        0
dtype: int64

In [17]:
data.shape

(9435, 9)


We replace the discount_price with the actual_price if it the value is missing because we assume that the price is not discounted.

In [10]:
data["discount_price"] = data["discount_price"].fillna(data["actual_price"])

In [11]:
data.isnull().sum()

name              0
main_category     0
sub_category      0
image             0
link              0
ratings           0
no_of_ratings     0
discount_price    0
actual_price      0
dtype: int64

## Handle Duplicates

Identify duplicates and remove them

We count how many fully duplicated rows exist

In [ ]:
print(data.duplicated().sum())

0

We have no duplicate rows, so no removal is needed.

## Handle Incorrect Data Types

In [19]:
data["ratings"].unique()

<StringArray>
['4.0', '4.3', '4.2', '4.1', '3.9', '4.6', '3.8', 'Get', '4.4', '3.5', '3.7',
 '4.5', '3.3', '3.6', '3.4', '3.2', '2.9', '4.7', '5.0', '2.5', '2.8', '4.8',
 '3.1', '3.0', '2.3', '2.7', '2.4', '4.9', '1.7', '1.5', '2.6', '1.8', '1.3',
 '2.1', '1.9', '2.2', '1.0', '1.4', '2.0']
Length: 39, dtype: str

## Handle Outliers

Identify outliers and remove or corret them

In [13]:
# TODO

## Visualize Data

Use graphes, plots and/or diagrams to visualize the data

In [14]:
# TODO

## Save Cleaned Data

In [15]:
# TODO